config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"

  ##############################
  # Map authentication routes to
  # the appropriate controller
  ##############################
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  delete "sign_out", to: "sessions#destroy"

  ##############################
  # Custom routes
  ##############################
  # Defines the path foe new user registration
  resource :registration, only: %i[new create]
  # Defines the path for the dashboard page
  resource :dashboard, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  MINIMUM_PASSWORD_LENGTH = 8

  has_secure_password
  has_many :sessions, dependent: :destroy

  validates :email_address, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }, confirmation: true
  validates :password_confirmation, presence: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to sign_in_url, alert: "You must sign in first."
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || dashboard_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  allow_unauthenticated_access

  def home
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to sign_in_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to sign_in_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access
  before_action :resume_session, only: :new
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to sign_up_url, alert: "Try again later." }

  def new
    redirect_to dashboard_url, notice: "You are already signed in." if authenticated?
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email_address, :password, :password_confirmation)
    user = User.new(user_params)
    if user.save
      start_new_session_for user
      redirect_to after_authentication_url, notice: "Signed up."
    else
      redirect_to sign_up_url(email_address: user_params[:email_address]), alert: user.errors.full_messages.to_sentence
    end
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to sign_in_url, alert: "Try again later." }

  def new
    @user = User.new
  end

  def create
    # Use `require` to target nested `:user` params, if form data is structured this way.
    user_params = params.require(:user).permit(:email_address, :password)

    if (user = User.authenticate_by(user_params))
      start_new_session_for user
      redirect_to after_authentication_url, notice: "Logged in with #{user.email_address}"
    else
      flash.now[:alert] = "Try another email address or password."
      redirect_to sign_in_url, status: :unprocessable_entity
    end
  end

  def destroy
    terminate_session
    redirect_to root_url, notice: "You have been signed out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end

  def form_error_notification(object)
    return unless object&.errors&.any? # Ensures object and errors are present

    tag.div class: "error-message" do
      object.errors.full_messages.to_sentence.capitalize
    end
  end
end

app/views/dashboards/show.html.erb
<%# app/views/dashboard.html.erb %>

<div class="dashboard">
  <h1 class="dashboard__header">
    Private Dashboard
  </h1>
  <p>
    Welcome <%= Current.user.email_address %>!
  </p>
  <p class="dashboard__description">
    This page should only be accessible to authenticated users.
  </p>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<%# app/views/shared/_navbar.html.erb %>

<header class="navbar">
  <div class="navbar__container">
    <div class="navbar__brand">
      <%= link_to "Micro Blog", root_path, class: "navbar__brand-link" %>
    </div>

    <nav class="navbar__nav">
      <ul class="navbar__list">
        <li class="navbar__item"><%= link_to "Home", root_path, class: "navbar__link" %></li>
        <% if authenticated? %>
          <li class="navbar__item"><%= link_to "Dashboard", dashboard_path, class: "navbar__link" %></li>
        <% end %>
      </ul>

      <ul class="navbar__list navbar__list--right">
        <% if authenticated? %>
          <li class="navbar__item navbar__name">
            <%= Current.user.email_address %>
          </li>
          <li class="navbar__item">
            <%= button_to "Sign out",
                          sign_out_path,
                          method: :delete,
                          class: "btn btn--dark" %>
          </li>
        <% else %>
          <li class="navbar__item">
            <%= link_to "Sign in",
                        sign_in_path,
                        class: "btn btn--dark" %>
          </li>
          <li class="navbar__item">
            <%= link_to "Sign up",
                        sign_up_path,
                        class: "btn btn--primary" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Micro Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing">
  <h1 class="landing__header">
    Landing Page
  </h1>
  <p class="landing__description">
    This page is public and can be accessed by both authenticated and unauthenticated users.
  </p>
</div>